### ISSUE TITLE
Dockerfile lacking some documentation

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-pelican#12]
The Dockerfile needs some explanation for future maintainers:

- why does it need a commit hash when building the image?
- why is it built in two stages?
- Why is it built from GitHub, rather than using the current checkout? Makes it harder to test changes

**Comment by dave2wave** [comment]
Each of these may be for developmental reasons.
* commit hash because a legacy gfm plugin configuration was used.
* two stages? @bdelacretaz 
* GitHub? PRs welcome

**Comment by sebbASF** [comment]
"commit hash because a legacy gfm plugin configuration was used."
What does that mean? does it still apply? How does one choose the correct hash?

**Comment by dave2wave** [comment]
The hash question is now moot since the Dockerfile uses the current checkout which can be any version the user wants.
Two stages are preferred since that saves 230 MB in image size. See PR #16 
The Dockerfile is now built from the local checkout.

**Comment by bdelacretaz** [comment]
> Two stages are preferred since that saves 230 MB in image size...

Yes, and if someone wants to make the final image smaller it should be possible to use a smaller base image than `python:3.9.5-slim-buster`. I'm not planning to try that myself at this time.
