### ISSUE TITLE
Add Twitter Secrets to Dockerfile?

### ISSUE THREAD

**Issue by dave2wave** [apache/infrastructure-pelican#14]
When using the Dockerfile to build a site that uses `asfdata.py` to retrieve tweets:
```
Traceback (most recent call last):
  File "/tmp/pelican-asf/bin/../plugins/asfdata.py", line 547, in twitter_auth
    for line in open(authtokens).readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/root/.authtokens'
```
Should the twitter secret bearer token be included in the Dockerfile? Can this be done securely? If so, how?

**Comment by dave2wave** [comment]
https://github.com/apache/infrastructure-pelican/blob/master/Dockerfile#L51

**Comment by sebbASF** [comment]
touch /root/.authtokens works for me: see PR #15

**Comment by dave2wave** [comment]
This doesn't improve the situation. It just hides that there is a problem. We need a way to install the file while building the Dockerfile image.

**Comment by dave2wave** [comment]
#15 now includes a way to get an .authtokens file into the image.

**Comment by sebbASF** [comment]
Don't the authtokens relate to the site rather than the pelican build software?

i.e. they should not be in the image, but should be picked up from the site instead.

**Comment by dave2wave** [comment]
No they are secrets for which a developer or organization is responsible for.

If the Docker image is going to be shared then we will need to confront this as something that is injected into the image with the command and not stored in the site's repository.

**Comment by dave2wave** [comment]
Dockerfile now has a link to .authtokens in the source directory. This is sufficient.
