### ISSUE TITLE
Do we need: git svn wget unzip?

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-pelican#17]
https://github.com/apache/infrastructure-pelican/blob/2af9eb42e3dc68e5fd355e63600bb5422593c4c5/Dockerfile#L50

Do we need to install the following:

git
subversion
wget
unzip

The site code is mapped to the container, so these tools can be used on the host if necessary.

Or are some of them needed by the pelican build itself?
In which case, this should be documented in the Dockerfile.

**Comment by sebbASF** [comment]
And what about fontconfig?

**Comment by dave2wave** [comment]
1. git is used by buildsite.py if it is run in git mode that emulates the buildbot.
2. subversion is used in the asfdata.py plugin for release data in template-site only.

wget, unzip, and fontconfig were provided by Bertrand. I'll have to experiment ...

**Comment by dave2wave** [comment]
It looks like we can remove wget, unzip, and fontconfig

**Comment by dave2wave** [comment]
See PR #20
