### ISSUE TITLE
Pelican command does not work

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-pelican#19]
https://github.com/apache/infrastructure-pelican/blob/e9e1d355e8b7c05de3a77883e132973eb2727cc2/Dockerfile#L33

The pelican command generates lots of errors, and does not create any output.
It needs a settings file.

**Comment by dave2wave** [comment]
Is the purpose of the Dockerfile to drive the creation of or just the testing of ASF Pelican sites?

In general ASF Pelican sites should be created from the template-site repository by either pressing the "Use this template" button or by copying files from a checkout.

**Comment by dave2wave** [comment]
See PR #20

**Comment by sebbASF** [comment]
It seems to me the purpose of the Dockerfile should be to allow testing of both the plugins and a site that uses those plugins.

In which case bare pelican commands are not really relevant, and could be dropped.
However, if it is desired to support the use of pelican directly, then the sample commands must actually work.

**Comment by dave2wave** [comment]
It's not currently desired to support all bare pelican commands. Once `buildsite.py dir` a settings file is present and that could be included on a pelican command line.
