### ISSUE TITLE
What is the purpose of this script?

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-pelican#23]
https://github.com/apache/infrastructure-pelican/blob/64bf5b809382b168789166740a47b187b472ce74/devtest/grab.sh#L3

**Comment by dave2wave** [comment]
Greg used this in development of buildsite.py

**Comment by sebbASF** [comment]
Can it be deleted then?

**Comment by gstein** [comment]
No. I intend to keep/improve the script to do large-scale testing of the pelican workflow.
