### ISSUE TITLE
asfgenid does not transform custom ids

### ISSUE THREAD

**Issue by sebbASF** [apache/infrastructure-pelican#74]
The asfgenid plugin is responsible for generating ids from header text, and also for using a custom id if specified.

It transforms the default id, but does not transform custom ids in the same way.

This is inconsistent.

**Comment by dave2wave** [comment]
Custom ids were designed to format anchors in the same way that the Apache CMS did in order to preserve historical links. If this is not what you are pointing out then could you be more specific about where in asfgenid the bug lies.
